import { describe, it, expect } from 'vitest';
import { parseCargoToml, readCargoLock } from '../../ecosystems/rust/parser';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

// ─── Helpers ─────────────────────────────────────────────────────────────────

function writeTempCargoToml(content: string): string {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'scanreq-test-'));
	const filePath = path.join(dir, 'Cargo.toml');
	fs.writeFileSync(filePath, content);
	return filePath;
}

/**
 * Crea un árbol de workspace simulado.
 * Devuelve la ruta al Cargo.toml indicado por `mainToml`.
 */
function writeWorkspaceTree(files: Record<string, string>, mainToml = 'Cargo.toml'): string {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'scanreq-rust-ws-'));
	for (const [relPath, content] of Object.entries(files)) {
		const abs = path.join(dir, relPath);
		fs.mkdirSync(path.dirname(abs), { recursive: true });
		fs.writeFileSync(abs, content);
	}
	return path.join(dir, mainToml);
}

// ─── parseCargoToml — tests existentes ───────────────────────────────────────

describe('parseCargoToml', () => {

	it('parsea versión exacta (solo número)', () => {
		const file = writeTempCargoToml(`[dependencies]\nserde = "1.0.195"`);
		const result = parseCargoToml(file);
		expect(result[0]).toMatchObject({ name: 'serde', version: '1.0.195', exactVersion: true });
	});

	it('parsea versión con ^ como no exacta', () => {
		const file = writeTempCargoToml(`[dependencies]\nserde = "^1.0"`);
		const result = parseCargoToml(file);
		expect(result[0]).toMatchObject({ name: 'serde', exactVersion: false, version: '1.0' });
	});

	it('parsea versión con ~ como no exacta', () => {
		const file = writeTempCargoToml(`[dependencies]\ntokio = "~1.35"`);
		const result = parseCargoToml(file);
		expect(result[0]).toMatchObject({ name: 'tokio', exactVersion: false });
	});

	it('parsea formato tabla { version = "..." }', () => {
		const file = writeTempCargoToml(`[dependencies]\nserde = { version = "1.0", features = ["derive"] }`);
		const result = parseCargoToml(file);
		expect(result[0]).toMatchObject({ name: 'serde', version: '1.0', exactVersion: false });
	});

	it('ignora workspace dependencies', () => {
		const file = writeTempCargoToml(`[dependencies]\nmylib = { workspace = true }`);
		const result = parseCargoToml(file);
		expect(result).toHaveLength(0);
	});

	it('ignora path dependencies', () => {
		const file = writeTempCargoToml(`[dependencies]\nmylib = { path = "../mylib" }`);
		const result = parseCargoToml(file);
		expect(result).toHaveLength(0);
	});

	it('parsea [dev-dependencies]', () => {
		const file = writeTempCargoToml(`[dev-dependencies]\nmockall = "0.12.0"`);
		const result = parseCargoToml(file);
		expect(result[0]).toMatchObject({ name: 'mockall', section: 'dev-dependencies' });
	});

	it('parsea [build-dependencies]', () => {
		const file = writeTempCargoToml(`[build-dependencies]\ncc = "1.0"`);
		const result = parseCargoToml(file);
		expect(result[0]).toMatchObject({ name: 'cc', section: 'build-dependencies' });
	});

	it('deduplica — dependencies tiene prioridad sobre dev-dependencies', () => {
		const file = writeTempCargoToml(`[dependencies]\nserde = "1.0.195"\n[dev-dependencies]\nserde = "1.0"`);
		const result = parseCargoToml(file);
		expect(result).toHaveLength(1);
		expect(result[0].section).toBe('dependencies');
		expect(result[0].exactVersion).toBe(true);
	});

	it('ignora comentarios', () => {
		const file = writeTempCargoToml(`[dependencies]\n# esto es un comentario\nserde = "1.0"`);
		const result = parseCargoToml(file);
		expect(result).toHaveLength(1);
	});

	it('parsea múltiples paquetes en la misma sección', () => {
		const file = writeTempCargoToml(`[dependencies]\nserde = "1.0"\ntokio = "1.35"\naxum = "0.7"`);
		const result = parseCargoToml(file);
		expect(result).toHaveLength(3);
		expect(result.map(p => p.name)).toEqual(['serde', 'tokio', 'axum']);
	});

	it('no parsea dependencias fuera de las secciones conocidas', () => {
		const file = writeTempCargoToml(`[package]\nname = "myapp"\nversion = "0.1.0"\n\n[dependencies]\nserde = "1.0"`);
		const result = parseCargoToml(file);
		expect(result).toHaveLength(1);
		expect(result[0].name).toBe('serde');
	});

	it('parsea versión con guiones en el nombre del crate', () => {
		const file = writeTempCargoToml(`[dependencies]\ntokio-util = "0.7.10"`);
		const result = parseCargoToml(file);
		expect(result[0].name).toBe('tokio-util');
	});
});

// ─── readCargoLock ────────────────────────────────────────────────────────────

describe('readCargoLock', () => {

	const LOCK_HEADER = `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n`;

	function lockBlock(name: string, version: string, source = 'registry+https://github.com/rust-lang/crates.io-index'): string {
		return `[[package]]\nname = "${name}"\nversion = "${version}"\nsource = "${source}"\n\n`;
	}

	it('lee un Cargo.lock en el mismo directorio que Cargo.toml', () => {
		const lock = LOCK_HEADER + lockBlock('serde', '1.0.197') + lockBlock('tokio', '1.36.0');
		const tomlPath = writeWorkspaceTree({
			'Cargo.toml': '[dependencies]\nserde = "^1.0"\ntokio = "^1.0"\n',
			'Cargo.lock': lock,
		});
		const map = readCargoLock(tomlPath);
		expect(map.get('serde')).toBe('1.0.197');
		expect(map.get('tokio')).toBe('1.36.0');
	});

	it('sube un nivel para encontrar el Cargo.lock del workspace (patrón veloren)', () => {
		const lock = LOCK_HEADER
			+ lockBlock('async-channel', '2.1.1')
			+ lockBlock('rustyline', '17.0.0')
			+ lockBlock('byteorder', '1.5.0');
		const tomlPath = writeWorkspaceTree({
			'Cargo.lock':           lock,
			'client/Cargo.toml':    '[dependencies]\nasync-channel = "~2.1"\nrustyline = "~17"\nbyteorder = "1.3.2"\n',
		}, 'client/Cargo.toml');
		const map = readCargoLock(tomlPath);
		expect(map.get('async-channel')).toBe('2.1.1');
		expect(map.get('rustyline')).toBe('17.0.0');
		expect(map.get('byteorder')).toBe('1.5.0');
	});

	it('sube dos niveles para encontrar el Cargo.lock (anidamiento profundo)', () => {
		const lock = LOCK_HEADER + lockBlock('serde', '1.0.197');
		const tomlPath = writeWorkspaceTree({
			'Cargo.lock':                   lock,
			'crates/core/Cargo.toml':       '[dependencies]\nserde = "^1.0"\n',
		}, 'crates/core/Cargo.toml');
		const map = readCargoLock(tomlPath);
		expect(map.get('serde')).toBe('1.0.197');
	});

	it('ignora paquetes locales (path+ source)', () => {
		const lock = LOCK_HEADER
			+ lockBlock('serde', '1.0.197')
			+ `[[package]]\nname = "my-local-crate"\nversion = "0.1.0"\nsource = "path+file:///home/user/project/my-local-crate"\n\n`;
		const tomlPath = writeWorkspaceTree({
			'Cargo.toml': '[dependencies]\nserde = "^1.0"\n',
			'Cargo.lock': lock,
		});
		const map = readCargoLock(tomlPath);
		expect(map.has('my-local-crate')).toBe(false);
		expect(map.get('serde')).toBe('1.0.197');
	});

	it('ignora paquetes sin source (workspace members)', () => {
		// Los crates miembros del workspace aparecen sin source en Cargo.lock
		const lock = LOCK_HEADER
			+ `[[package]]\nname = "my-app"\nversion = "0.1.0"\n\n`
			+ lockBlock('serde', '1.0.197');
		const tomlPath = writeWorkspaceTree({
			'Cargo.toml': '[dependencies]\nserde = "^1.0"\n',
			'Cargo.lock': lock,
		});
		const map = readCargoLock(tomlPath);
		expect(map.has('my-app')).toBe(false);
		expect(map.get('serde')).toBe('1.0.197');
	});

	it('cuando hay múltiples versiones del mismo crate, toma la primera', () => {
		// Situación real: el grafo de deps puede tener dos versiones de un crate
		const lock = LOCK_HEADER
			+ lockBlock('rand', '0.7.3')
			+ lockBlock('rand', '0.8.5');
		const tomlPath = writeWorkspaceTree({
			'Cargo.toml': '[dependencies]\nrand = "^0.8"\n',
			'Cargo.lock': lock,
		});
		const map = readCargoLock(tomlPath);
		expect(map.get('rand')).toBe('0.7.3'); // primera entrada gana
	});

	it('devuelve mapa vacío si no existe Cargo.lock', () => {
		const tomlPath = writeWorkspaceTree({
			'Cargo.toml': '[dependencies]\nserde = "^1.0"\n',
		});
		const map = readCargoLock(tomlPath);
		expect(map.size).toBe(0);
	});

	it('devuelve mapa vacío si la ruta no existe', () => {
		const map = readCargoLock('/ruta/inexistente/Cargo.toml');
		expect(map.size).toBe(0);
	});
});
